### ISSUE TITLE
Introduction of README.ipynb

### ISSUE THREAD

**Issue by 8rV1n** [Dawn-Team/learning-materials#1]
The Introduction Chapter.

**Comment by 8rV1n** [comment]
Introduction should also include the Introduction for Jupyter.  
The chapter number should be `1` and `2`.

**Comment by 8rV1n** [comment]
@Ash-Morgan This chapter is now available for review, please schedule it when you are convenient.

**Comment by 8rV1n** [comment]
@Ash-Morgan Few cite tags are updated, please check the latest version for chap `1` and `2`.

**Comment by Ash-Morgan** [comment]
I have checked these chap.They were OK. @ArvinSiChuan

**Comment by 8rV1n** [comment]
Two inner version of the doc have passed, this chap should be OK.
