### ISSUE TITLE
Our Jupyter Platform Guidelines

### ISSUE THREAD

**Issue by 8rV1n** [Dawn-Team/learning-materials#2]
Guidelines for using ourselves' platform. 
Chapter Number should be  `3`.

**Comment by 8rV1n** [comment]
@Ash-Morgan By the commit 965a0b25bf722566cf2f54c521c12d6de760720c, Chapter `3` is available for reviewing.  
Main content about this part is how to authorize our platfrom ,use shell, embed github service and etc.

**Comment by Ash-Morgan** [comment]
I have checked chap 3 and i will try it late.

**Comment by 8rV1n** [comment]
Two innder version of the file have been passed, it should be fine.
